apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-app
spec:
  selector:
    matchLabels:
      app: devops-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: devops-test-app
    spec:
      containers:
        - name: devops-test-app
          image: gcr.io/buildit-devops/devops-test

